name: Empaquetar WebApp como APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Instalar Capacitor Android
        run: npm run android

      - name: Instalar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: WebApp-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
